title: <p align="center"> Ngan Pham </p>

logo: "/images/avatar.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ngan-pham-2a499716b/">LinkedIn</a> |
  <a href="https://github.com/npham25">GitHub</a>
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="6503019d-6c86-471d-9b57-b8407a47010b" data-share-badge-host="https://www.youracclaim.com"></div><script type="text/javascript" async src="//cdn.youracclaim.com/assets/utilities/embed.js"></script>
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="fcb401cf-083a-4ca2-8935-236295a18752" data-share-badge-host="https://www.youracclaim.com"></div><script type="text/javascript" async src="//cdn.youracclaim.com/assets/utilities/embed.js"></script>
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="5fafe53f-c6b1-4831-ad3d-18b06f7690a8" data-share-badge-host="https://www.youracclaim.com"></div><script type="text/javascript" async src="//cdn.youracclaim.com/assets/utilities/embed.js"></script>
  </p>
  
  <p align="justify">
  I am a PhD Student in Applied Statistics at University of Memphis
  <br><br>
  I am currently a Research Assistatnt at Division of Epidemiology, Biostatistics, and Environmental Health, UofM. 
  I have 5+ years experience in data analytics.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
