title: <p align="center"> Myra(Ngan) Pham </p>

logo: "/images/profile-pic-2.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/myra-ngan-pham-2a499716b/">LinkedIn</a> |
  <a href="https://github.com/npham25">GitHub</a>
  </p>
  
  <p align="justify">
  I am a PhD Student in Applied Statistics at University of Memphis
  <br><br>
  I am currently a Research Assistant at Division of Epidemiology, Biostatistics, and Environmental Health, UofM<br/>
  I have 5+ years experience in data analytics<br/>
  My interests are Data Science and Biostatistics
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
